### PR TITLE
[WIP]chore: Add ieee sight page

### PR DESCRIPTION
**Pull request by shaista1519**

### CODE REVIEW

**Review by pnijhara — COMMENTED** [review]
Appreciable work, though it still needs some changes.

**Comment by pnijhara** [comment]
@shaista1519 why did you close this PR?

**Comment by shaista1519** [comment]
Ill re send it tomorrow.Actually I was trying to pull the updated code but
ended up with nothing.😳

**Comment by pnijhara** [comment]
All the best!

**Pull request closed without merging**
